---
title: "Week 2 Milestone"
author: "Sarah E. Wright"
date: "Dec 29, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(quanteda)
library(data.table)
library(plotly)
source("DataImport.R")
source("MakeNGrams.R")

```

## Import data and make, clean up, and summarize n-grams
```{r dataprocessing}
work.dir <- "C:/Users/sewright/Documents/R/Classes/CourseraDataScienceCapstone"
line.counts <- DataImport(work.dir)
MakeNGrams(work.dir)
```

## Summary of Raw Data

```{r summary, echo = FALSE}
# Line count for each file
line.counts
# Word count for each file

# Table of file, size, line count, and word count

```

## Data Cleaning and Processing

### Tokenization

### Making n-grams

### Cleaning up n-grams

```{r include = FALSE}
# Plot showing size of object vs % of words covered

# Read in 1- through 4-grams
one.grams <- fread("one_grams.txt")
two.grams <- fread("two_grams.txt")
three.grams <- fread("three_grams.txt")
four.grams <- fread("four_grams.txt")

# Calculate total occurrences of all n-grams
n.one.grams <- sum(one.grams$count)
n.two.grams <- sum(two.grams$count)
n.three.grams <- sum(three.grams$count)
n.four.grams <- sum(four.grams$count)

# Print number of n-grams that cover 90% of occurrences
nrow(one.grams[cumulative.proportion <= 0.90])
nrow(two.grams[cumulative.proportion <= 0.90])
nrow(three.grams[cumulative.proportion <= 0.90])
nrow(four.grams[cumulative.proportion <= 0.90])

# Plot file size vs percentage of corpus covered
acc.data <- data.frame()
for (pct in seq(0.1, 0.9, 0.1)) {
    one.grams.size <- object.size(one.grams[cumulative.proportion <= pct])
    two.grams.size <- object.size(two.grams[cumulative.proportion <= pct])
    three.grams.size <- object.size(three.grams[cumulative.proportion <= pct])
    four.grams.size <- object.size(four.grams[cumulative.proportion <= pct])
    acc.data <- rbind(acc.data, c(pct, one.grams.size, two.grams.size, three.grams.size, four.grams.size))
}
names(acc.data) <- c("proportion", "one.grams.size", "two.grams.size", "three.grams.size", "four.grams.size")
acc.data[,2:5] <- acc.data[,2:5]/1000000000

plot_ly(data = acc.data, x = ~percent) %>%
    add_trace(y = ~one.grams.size, name = "one-grams size (Gb)") %>%
    add_trace(y = ~two.grams.size, name = "two-grams size (Gb)") %>%
    add_trace(y = ~three.grams.size, name = "three-grams size (Gb)") %>%
    add_trace(y = ~four.grams.size, name = "four-grams size (Gb)")

# Plots of n-gram frequencies

```
 

## Prediction Algorithm and App

### Algorithm

### Shiny App